import bcrypt from 'bcrypt';
import { UserModel } from '../modules/auth/user.model.js';
import { ActivityModel } from '../modules/activities/activity.model.js';
import { RegistrationModel } from '../modules/registrations/registration.model.js';
import { TeamModel } from '../modules/activities/team.model.js';
import { ActivityFormat, ActivityStatus, JoinMode, RegistrationStatus, UserRole } from '@gathergrid/shared';
import { logger } from '../common/logger.js';

export async function seedDatabase(): Promise<void> {
  try {
    const activityCount = await ActivityModel.countDocuments();
    if (activityCount > 0) {
      // DB already seeded
      return;
    }

    logger.info('Populating database with seed accounts, activities, teams, and registrations...');
    const salt = await bcrypt.genSalt(10);

    // ── 1. Admin Account ───────────────────────────────────────────
    const adminPasswordHash = await bcrypt.hash('AdminPass123!', salt);
    const hostPasswordHash = await bcrypt.hash('HostPass123!', salt);
    const userPasswordHash = await bcrypt.hash('UserPass123!', salt);

    await UserModel.create({
      name: 'GatherGrid Platform Admin',
      email: 'admin@gathergrid.com',
      passwordHash: adminPasswordHash,
      role: UserRole.ADMIN,
      isVerified: true,
      bio: 'Lead system administrator and trust & safety officer.',
      avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80',
      defaultRadiusKm: 50,
    });

    // ── 2. Organizer Accounts ──────────────────────────────────────
    const org1 = await UserModel.create({
      name: 'Sarah Jenkins',
      email: 'host.sarah@bayareaoutdoors.com',
      passwordHash: hostPasswordHash,
      role: UserRole.ORGANIZER,
      isVerified: true,
      organizationName: 'Bay Area Outdoor Club',
      bio: 'Leading outdoor adventures, beach volleyball, and coastal hiking expeditions across San Francisco and Marin County since 2021.',
      avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&auto=format&fit=crop&q=80',
      interests: ['hiking', 'volleyball', 'camping', 'kayaking'],
      defaultRadiusKm: 35,
    });

    const org2 = await UserModel.create({
      name: 'Alex Chen',
      email: 'alex@sfhack.io',
      passwordHash: hostPasswordHash,
      role: UserRole.ORGANIZER,
      isVerified: true,
      organizationName: 'SF Tech & Hackathons',
      bio: 'Community builder organizing open-source AI sprints, developer workshops, and civic tech hackathons in SoMa and Downtown SF.',
      avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80',
      interests: ['ai', 'hackathons', 'coding', 'startups'],
      defaultRadiusKm: 25,
    });

    const org3 = await UserModel.create({
      name: 'Marcus Vance',
      email: 'marcus@missiongames.org',
      passwordHash: hostPasswordHash,
      role: UserRole.ORGANIZER,
      isVerified: true,
      organizationName: 'Mission Board Game Guild',
      bio: 'Passionate Eurogame collector and game designer hosting weekly tabletop socials, strategy battles, and indie game testing nights.',
      avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&auto=format&fit=crop&q=80',
      interests: ['boardgames', 'catan', 'chess', 'tabletop'],
      defaultRadiusKm: 20,
    });

    const org4 = await UserModel.create({
      name: 'Elena Rostova',
      email: 'elena@craftworkssf.com',
      passwordHash: hostPasswordHash,
      role: UserRole.ORGANIZER,
      isVerified: true,
      organizationName: 'SF Artisan Workshops',
      bio: 'Ceramics instructor and stained glass artist creating community art spaces in the Dogpatch and Mission craft lofts.',
      avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=200&auto=format&fit=crop&q=80',
      interests: ['pottery', 'crafts', 'art', 'woodworking'],
      defaultRadiusKm: 20,
    });

    // ── 3. Participant Accounts ────────────────────────────────────
    const participant1 = await UserModel.create({
      name: 'Jordan Taylor',
      email: 'participant@gathergrid.com',
      passwordHash: userPasswordHash,
      role: UserRole.PARTICIPANT,
      isVerified: true,
      bio: 'Avid weekend hiker and software engineer exploring the city.',
      avatarUrl: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=200&auto=format&fit=crop&q=80',
      interests: ['sports', 'hackathons', 'gaming'],
      defaultRadiusKm: 25,
    });

    const participant2 = await UserModel.create({
      name: 'Maya Patel',
      email: 'maya.patel@example.com',
      passwordHash: userPasswordHash,
      role: UserRole.PARTICIPANT,
      isVerified: true,
      bio: 'Product designer interested in community arts and beach volleyball.',
      avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=200&auto=format&fit=crop&q=80',
      interests: ['sports', 'workshops', 'social'],
      defaultRadiusKm: 20,
    });

    const participant3 = await UserModel.create({
      name: 'Liam Nguyen',
      email: 'liam.nguyen@example.com',
      passwordHash: userPasswordHash,
      role: UserRole.PARTICIPANT,
      isVerified: true,
      bio: 'Fullstack developer & board game enthusiast.',
      avatarUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=200&auto=format&fit=crop&q=80',
      interests: ['hackathons', 'gaming', 'tech'],
      defaultRadiusKm: 30,
    });

    // ── 4. Activities Seed Data ────────────────────────────────────
    const activitiesData = [
      {
        id: 'act-1',
        title: 'Sunset Beach Volleyball & Social',
        categorySlug: 'sports',
        categoryLabel: 'Sports',
        categoryEmoji: '🏐',
        shortDescription: 'Casual 4v4 beach volleyball games followed by a sunset bonfire social.',
        fullDescription: 'Join us for fun games on the sand! All skill levels welcome. We have two nets set up. Bring water, sunscreen, and snacks to share around the fire pits after the matches.',
        format: ActivityFormat.IN_PERSON,
        locationName: 'Ocean Beach, San Francisco',
        address: 'Great Hwy & Fulton St, San Francisco, CA',
        lat: 37.7719,
        lng: -122.5113,
        startDateTime: '2026-10-25T16:00:00Z',
        endDateTime: '2026-10-25T19:00:00Z',
        timezone: 'America/Los_Angeles',
        capacity: 24,
        registeredCount: 16,
        waitlistCount: 2,
        joinMode: JoinMode.INSTANT,
        waitlistEnabled: true,
        isTeamEvent: false,
        costInfo: 'Free',
        bannerUrl: 'https://images.unsplash.com/photo-1612872087720-bb876e2e67d1?w=800&auto=format&fit=crop&q=80',
        tags: ['volleyball', 'beach', 'sunset', 'social'],
        status: ActivityStatus.PUBLISHED,
        organizerId: org1._id.toString(),
        organizerName: org1.organizationName || org1.name,
        organizerBadge: 'gold',
        createdAt: '2026-10-01T10:00:00Z',
      },
      {
        id: 'act-2',
        title: 'Autumn Hackathon: AI for Good',
        categorySlug: 'hackathons',
        categoryLabel: 'Hackathons',
        categoryEmoji: '💻',
        shortDescription: '36-hour sprint building open-source AI solutions for civic & climate challenges.',
        fullDescription: 'Form teams of 2-5 builders and create high-impact prototypes. Free food, mentor support from top researchers, hardware access, and $10k in grants for top projects.',
        format: ActivityFormat.IN_PERSON,
        locationName: 'SF Innovation Hub, SoMa',
        address: '500 Howard St, San Francisco, CA',
        lat: 37.7891,
        lng: -122.3982,
        startDateTime: '2026-10-28T09:00:00Z',
        endDateTime: '2026-10-29T18:00:00Z',
        timezone: 'America/Los_Angeles',
        capacity: 40,
        registeredCount: 22,
        waitlistCount: 0,
        joinMode: JoinMode.APPROVAL,
        waitlistEnabled: true,
        isTeamEvent: true,
        costInfo: 'Free',
        bannerUrl: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=800&auto=format&fit=crop&q=80',
        tags: ['ai', 'hackathon', 'coding', 'teams'],
        status: ActivityStatus.PUBLISHED,
        organizerId: org2._id.toString(),
        organizerName: org2.organizationName || org2.name,
        organizerBadge: 'silver',
        createdAt: '2026-10-02T12:00:00Z',
      },
      {
        id: 'act-3',
        title: 'Strategy Board Game & Eurogame Night',
        categorySlug: 'gaming',
        categoryLabel: 'Gaming',
        categoryEmoji: '🎲',
        shortDescription: 'Weekly tabletop meetup featuring Catan, Dune Imperium, Terraforming Mars, and Wingspan.',
        fullDescription: 'Bring your favorite strategy games or join one of our hosted tables! Friendly teaching tables for newcomers, competitive tables for veterans. Café drinks and craft beer available.',
        format: ActivityFormat.IN_PERSON,
        locationName: 'Gamescape & Mission Loft',
        address: '333 Divisadero St, San Francisco, CA',
        lat: 37.7725,
        lng: -122.4372,
        startDateTime: '2026-10-26T18:30:00Z',
        endDateTime: '2026-10-26T22:30:00Z',
        timezone: 'America/Los_Angeles',
        capacity: 30,
        registeredCount: 20,
        waitlistCount: 1,
        joinMode: JoinMode.INSTANT,
        waitlistEnabled: true,
        isTeamEvent: false,
        costInfo: '$5 (supports venue space)',
        bannerUrl: 'https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?w=800&auto=format&fit=crop&q=80',
        tags: ['boardgames', 'catan', 'tabletop', 'social'],
        status: ActivityStatus.PUBLISHED,
        organizerId: org3._id.toString(),
        organizerName: org3.organizationName || org3.name,
        organizerBadge: 'bronze',
        createdAt: '2026-10-03T15:00:00Z',
      },
      {
        id: 'act-4',
        title: 'Wheel Throwing Pottery & Ceramics Workshop',
        categorySlug: 'workshops',
        categoryLabel: 'Workshops',
        categoryEmoji: '🛠️',
        shortDescription: 'Hands-on beginner ceramic wheel throwing session with clay, glaze, and firing included.',
        fullDescription: 'Learn pottery fundamentals! You will throw 2-3 pieces on the wheel, trim them, and select glazes. Studio technicians will fire your finished ceramics for pickup.',
        format: ActivityFormat.IN_PERSON,
        locationName: 'Clayroom Dogpatch Studio',
        address: '2295 3rd St, San Francisco, CA',
        lat: 37.7613,
        lng: -122.3882,
        startDateTime: '2026-10-27T14:00:00Z',
        endDateTime: '2026-10-27T17:00:00Z',
        timezone: 'America/Los_Angeles',
        capacity: 12,
        registeredCount: 10,
        waitlistCount: 3,
        joinMode: JoinMode.APPROVAL,
        waitlistEnabled: true,
        isTeamEvent: false,
        costInfo: '$45 (includes materials & firing)',
        bannerUrl: 'https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=800&auto=format&fit=crop&q=80',
        tags: ['pottery', 'ceramics', 'art', 'hands-on'],
        status: ActivityStatus.PUBLISHED,
        organizerId: org4._id.toString(),
        organizerName: org4.organizationName || org4.name,
        organizerBadge: 'new',
        createdAt: '2026-10-04T11:00:00Z',
      },
      {
        id: 'act-5',
        title: 'Golden Gate Park Trail Run & Breakfast',
        categorySlug: 'sports',
        categoryLabel: 'Sports',
        categoryEmoji: '🏃',
        shortDescription: 'Scenic 7km morning loop through Golden Gate Park followed by artisan coffee.',
        fullDescription: 'Starting from Conservatory of Flowers, running past Stow Lake and Rose Garden at a conversational 6:00/km pace. Open to all runners.',
        format: ActivityFormat.IN_PERSON,
        locationName: 'Golden Gate Park Conservatory',
        address: '100 John F Kennedy Dr, San Francisco, CA',
        lat: 37.7726,
        lng: -122.4601,
        startDateTime: '2026-10-31T08:00:00Z',
        endDateTime: '2026-10-31T10:00:00Z',
        timezone: 'America/Los_Angeles',
        capacity: 25,
        registeredCount: 15,
        waitlistCount: 0,
        joinMode: JoinMode.INSTANT,
        waitlistEnabled: true,
        isTeamEvent: false,
        costInfo: 'Free',
        bannerUrl: 'https://images.unsplash.com/photo-1452626038306-9aae5e071dd3?w=800&auto=format&fit=crop&q=80',
        tags: ['running', 'morning', 'fitness', 'nature'],
        status: ActivityStatus.PUBLISHED,
        organizerId: org1._id.toString(),
        organizerName: org1.organizationName || org1.name,
        organizerBadge: 'gold',
        createdAt: '2026-10-04T16:00:00Z',
      },
      {
        id: 'act-6',
        title: 'WebGPU & Modern Graphics Online Masterclass',
        categorySlug: 'workshops',
        categoryLabel: 'Workshops',
        categoryEmoji: '🌐',
        shortDescription: 'Deep dive into shader programming and next-gen browser 3D with WebGPU.',
        fullDescription: 'Interactive coding lab building real-time compute shaders and render pipelines in TypeScript. Live Q&A, Discord lounge, and starter boilerplate provided.',
        format: ActivityFormat.ONLINE,
        locationName: 'Zoom & Discord Live Workshop',
        onlinePlatform: 'Zoom + Discord',
        startDateTime: '2026-10-29T19:00:00Z',
        endDateTime: '2026-10-29T21:30:00Z',
        timezone: 'America/Los_Angeles',
        capacity: 100,
        registeredCount: 54,
        waitlistCount: 0,
        joinMode: JoinMode.INSTANT,
        waitlistEnabled: false,
        isTeamEvent: false,
        costInfo: 'Free',
        bannerUrl: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=800&auto=format&fit=crop&q=80',
        tags: ['webgpu', 'graphics', 'typescript', 'virtual'],
        status: ActivityStatus.PUBLISHED,
        organizerId: org2._id.toString(),
        organizerName: org2.organizationName || org2.name,
        organizerBadge: 'silver',
        createdAt: '2026-10-05T09:00:00Z',
      },
      {
        id: 'act-7',
        title: 'Bay Area 3v3 Beach Volleyball Showdown',
        categorySlug: 'sports',
        categoryLabel: 'Sports',
        categoryEmoji: '🏐',
        shortDescription: 'Competitive 3v3 beach tournament with pool play and knockout bracket.',
        fullDescription: 'Assemble your team of 3 players! Double elimination bracket, referee coverage, hydration station, and championship medals for 1st & 2nd place.',
        format: ActivityFormat.IN_PERSON,
        locationName: 'Ocean Beach Volleyball Courts',
        address: 'Ocean Beach Pier, San Francisco, CA',
        lat: 37.7719,
        lng: -122.5113,
        startDateTime: '2026-11-01T10:00:00Z',
        endDateTime: '2026-11-01T16:00:00Z',
        timezone: 'America/Los_Angeles',
        capacity: 24,
        registeredCount: 18,
        waitlistCount: 3,
        joinMode: JoinMode.APPROVAL,
        waitlistEnabled: true,
        isTeamEvent: true,
        costInfo: '$15 per team',
        bannerUrl: 'https://images.unsplash.com/photo-1592656094267-764a45160876?w=800&auto=format&fit=crop&q=80',
        tags: ['volleyball', 'tournament', 'teams', 'competitive'],
        status: ActivityStatus.PUBLISHED,
        organizerId: org1._id.toString(),
        organizerName: org1.organizationName || org1.name,
        organizerBadge: 'gold',
        createdAt: '2026-10-05T14:00:00Z',
      },
      {
        id: 'act-8',
        title: 'Indie Game Jam 48-Hour Sprint',
        categorySlug: 'gaming',
        categoryLabel: 'Gaming',
        categoryEmoji: '🕹️',
        shortDescription: 'Build a playable game in 48 hours around a secret theme. Teams of 2-4.',
        fullDescription: 'Music composers, artists, programmers, and storytellers collaborate to create indie gems in Godot, Unity, or Phaser. Online showcase on Sunday night with community voting.',
        format: ActivityFormat.ONLINE,
        locationName: 'GatherGrid Discord Jam Arena',
        onlinePlatform: 'Discord & Itch.io',
        startDateTime: '2026-11-06T18:00:00Z',
        endDateTime: '2026-11-08T20:00:00Z',
        timezone: 'America/Los_Angeles',
        capacity: 60,
        registeredCount: 34,
        waitlistCount: 0,
        joinMode: JoinMode.INSTANT,
        waitlistEnabled: true,
        isTeamEvent: true,
        costInfo: 'Free',
        bannerUrl: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=800&auto=format&fit=crop&q=80',
        tags: ['gamedev', 'jam', 'indie', 'teams'],
        status: ActivityStatus.PUBLISHED,
        organizerId: org3._id.toString(),
        organizerName: org3.organizationName || org3.name,
        organizerBadge: 'bronze',
        createdAt: '2026-10-06T08:00:00Z',
      },
      // ── Past Events for Organizers (so participants see past activities) ──
      {
        id: 'act-past-1',
        title: 'Summer Marin Headlands Coastal Hike',
        categorySlug: 'sports',
        categoryLabel: 'Sports',
        categoryEmoji: '🥾',
        shortDescription: '12km coastal trail loop with panoramic Golden Gate views.',
        fullDescription: 'Completed in September with 30 attendees. Amazing weather and foggy views across the headlands.',
        format: ActivityFormat.IN_PERSON,
        locationName: 'Marin Headlands Visitor Center',
        address: '948 Fort Barry, Sausalito, CA',
        lat: 37.8324,
        lng: -122.5312,
        startDateTime: '2026-09-12T09:00:00Z',
        endDateTime: '2026-09-12T14:00:00Z',
        timezone: 'America/Los_Angeles',
        capacity: 30,
        registeredCount: 30,
        waitlistCount: 5,
        joinMode: JoinMode.INSTANT,
        waitlistEnabled: true,
        isTeamEvent: false,
        costInfo: 'Free',
        bannerUrl: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&auto=format&fit=crop&q=80',
        tags: ['hiking', 'marin', 'coastal', 'scenic'],
        status: ActivityStatus.COMPLETED,
        organizerId: org1._id.toString(),
        organizerName: org1.organizationName || org1.name,
        organizerBadge: 'gold',
        createdAt: '2026-08-20T10:00:00Z',
      },
      {
        id: 'act-past-2',
        title: 'Open Source LLMs & Fine-Tuning Summit',
        categorySlug: 'hackathons',
        categoryLabel: 'Hackathons',
        categoryEmoji: '🤖',
        shortDescription: 'Hands-on workshop benchmarking open weights on local GPUs.',
        fullDescription: 'Completed in September with 40 participants exploring quantized weights and synthetic data generation.',
        format: ActivityFormat.IN_PERSON,
        locationName: 'Salesforce Tower Community Space',
        address: '415 Mission St, San Francisco, CA',
        lat: 37.7897,
        lng: -122.3972,
        startDateTime: '2026-09-19T10:00:00Z',
        endDateTime: '2026-09-19T17:00:00Z',
        timezone: 'America/Los_Angeles',
        capacity: 40,
        registeredCount: 40,
        waitlistCount: 12,
        joinMode: JoinMode.APPROVAL,
        waitlistEnabled: true,
        isTeamEvent: false,
        costInfo: 'Free',
        bannerUrl: 'https://images.unsplash.com/photo-1531482615713-2afd69097998?w=800&auto=format&fit=crop&q=80',
        tags: ['ai', 'llm', 'developers', 'summit'],
        status: ActivityStatus.COMPLETED,
        organizerId: org2._id.toString(),
        organizerName: org2.organizationName || org2.name,
        organizerBadge: 'silver',
        createdAt: '2026-08-25T14:00:00Z',
      },
    ];

    await ActivityModel.insertMany(activitiesData);

    // ── 5. Teams for Team-Based Activities ──────────────────────────
    const teamsData = [
      {
        id: 'team-1',
        activityId: 'act-2',
        name: 'EcoAgents AI',
        description: 'Building multi-agent systems for local wildfire prevention & sensor analysis.',
        leaderId: participant1._id.toString(),
        leaderName: participant1.name,
        members: [
          { userId: participant1._id.toString(), userName: participant1.name, role: 'Lead Architect', avatarUrl: participant1.avatarUrl },
          { userId: participant2._id.toString(), userName: participant2.name, role: 'Product & UX', avatarUrl: participant2.avatarUrl },
        ],
        maxMembers: 4,
        lookingFor: ['PyTorch Developer', 'Data Engineer'],
        joinCode: 'ECO2026',
      },
      {
        id: 'team-2',
        activityId: 'act-2',
        name: 'CivicPulse SF',
        description: 'Real-time city services accessibility dashboard powered by local LLMs.',
        leaderId: participant3._id.toString(),
        leaderName: participant3.name,
        members: [
          { userId: participant3._id.toString(), userName: participant3.name, role: 'Fullstack Dev', avatarUrl: participant3.avatarUrl },
        ],
        maxMembers: 4,
        lookingFor: ['Frontend React Dev', 'UI Designer'],
        joinCode: 'CIVIC77',
      },
      {
        id: 'team-3',
        activityId: 'act-7',
        name: 'Pacific Spike Trio',
        description: 'Solid defense and high energy beach volleyball trio.',
        leaderId: participant2._id.toString(),
        leaderName: participant2.name,
        members: [
          { userId: participant2._id.toString(), userName: participant2.name, role: 'Setter', avatarUrl: participant2.avatarUrl },
          { userId: participant1._id.toString(), userName: participant1.name, role: 'Outside Hitter', avatarUrl: participant1.avatarUrl },
        ],
        maxMembers: 3,
        lookingFor: ['Blocker'],
        joinCode: 'SPIKE3',
      },
      {
        id: 'team-4',
        activityId: 'act-8',
        name: 'PixelForge Studios',
        description: 'Creating a retro 2D narrative mystery game in Godot 4.',
        leaderId: participant1._id.toString(),
        leaderName: participant1.name,
        members: [
          { userId: participant1._id.toString(), userName: participant1.name, role: 'Programmer', avatarUrl: participant1.avatarUrl },
          { userId: participant3._id.toString(), userName: participant3.name, role: 'Sound & Music', avatarUrl: participant3.avatarUrl },
        ],
        maxMembers: 4,
        lookingFor: ['Pixel Artist', 'Story Writer'],
        joinCode: 'PIXEL9',
      },
    ];

    await TeamModel.insertMany(teamsData);

    // ── 6. Registrations ───────────────────────────────────────────
    const registrationsData = [
      {
        id: 'reg-1',
        activityId: 'act-1',
        userId: participant1._id.toString(),
        userName: participant1.name,
        userEmail: participant1.email,
        userAvatarUrl: participant1.avatarUrl,
        status: RegistrationStatus.CONFIRMED,
        appliedAt: '2026-10-05T14:00:00Z',
        confirmedAt: '2026-10-05T14:00:00Z',
      },
      {
        id: 'reg-2',
        activityId: 'act-2',
        userId: participant1._id.toString(),
        userName: participant1.name,
        userEmail: participant1.email,
        userAvatarUrl: participant1.avatarUrl,
        status: RegistrationStatus.CONFIRMED,
        appliedAt: '2026-10-05T15:00:00Z',
        confirmedAt: '2026-10-06T09:00:00Z',
        teamId: 'team-1',
        teamName: 'EcoAgents AI',
      },
      {
        id: 'reg-3',
        activityId: 'act-2',
        userId: participant2._id.toString(),
        userName: participant2.name,
        userEmail: participant2.email,
        userAvatarUrl: participant2.avatarUrl,
        status: RegistrationStatus.CONFIRMED,
        appliedAt: '2026-10-05T15:30:00Z',
        confirmedAt: '2026-10-06T09:30:00Z',
        teamId: 'team-1',
        teamName: 'EcoAgents AI',
      },
      {
        id: 'reg-4',
        activityId: 'act-2',
        userId: participant3._id.toString(),
        userName: participant3.name,
        userEmail: participant3.email,
        userAvatarUrl: participant3.avatarUrl,
        status: RegistrationStatus.PENDING,
        appliedAt: '2026-10-07T11:00:00Z',
        teamId: 'team-2',
        teamName: 'CivicPulse SF',
      },
      {
        id: 'reg-5',
        activityId: 'act-3',
        userId: participant1._id.toString(),
        userName: participant1.name,
        userEmail: participant1.email,
        userAvatarUrl: participant1.avatarUrl,
        status: RegistrationStatus.WAITLISTED,
        waitlistPosition: 1,
        appliedAt: '2026-10-06T10:00:00Z',
      },
      {
        id: 'reg-6',
        activityId: 'act-4',
        userId: participant2._id.toString(),
        userName: participant2.name,
        userEmail: participant2.email,
        userAvatarUrl: participant2.avatarUrl,
        status: RegistrationStatus.PENDING,
        appliedAt: '2026-10-07T12:00:00Z',
      },
      {
        id: 'reg-7',
        activityId: 'act-7',
        userId: participant2._id.toString(),
        userName: participant2.name,
        userEmail: participant2.email,
        userAvatarUrl: participant2.avatarUrl,
        status: RegistrationStatus.CONFIRMED,
        appliedAt: '2026-10-06T14:00:00Z',
        confirmedAt: '2026-10-06T16:00:00Z',
        teamId: 'team-3',
        teamName: 'Pacific Spike Trio',
      },
    ];

    await RegistrationModel.insertMany(registrationsData);

    logger.info('Database seeded successfully with persistent models and relations!');
  } catch (err: unknown) {
    logger.error({ err }, 'Failed to seed database');
  }
}
